apiVersion: v1
kind: Service
metadata:
  name: gokteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "gokteto"
    port: 8080
  selector:
    app: gokteto
